[agent]
model = "gpt-4"
temperature = 0.1
max_tokens = 4000

[parser_service]
base_url = "http://localhost:5001"
timeout = 30
retry_attempts = 3

[deployment]
environment = "production"
log_level = "INFO" 